In [1]:
import pandas as pd 
import numpy as np 

univ = ['SPY','TLT','VXX','QQQ']
dates = ['20210105','20210106','20210107','20210108','20210109']

In [2]:
earnings = pd.DataFrame(np.random.randn(5,4), index=dates,columns=univ)
ret_prev = pd.DataFrame(np.random.randn(5,4), index=dates,columns=univ)
pe = pd.DataFrame( np.random.randn(5,4), index=dates,columns=univ)
analyst_est = pd.DataFrame( np.random.randn(5,4), index=dates,columns=univ)

In [3]:
pe

               SPY       TLT       VXX       QQQ
20210105 -0.207814 -0.970921  0.643785  0.113942
20210106  0.013770 -1.006029  1.360488  0.376946
20210107  0.807295  0.336137  1.353254 -0.067273
20210108 -0.590600 -1.808742 -1.213458 -1.056192
20210109  1.072926  1.209638 -0.264925 -1.300229

In [4]:
data = {}
data['earnings']=earnings
data['ret_prev']=ret_prev
data['pe']=pe
data['analyst_est']=analyst_est

In [5]:
data

{'earnings':                SPY       TLT       VXX       QQQ
 20210105  1.202382  0.388800 -1.921227 -0.897985
 20210106 -0.896041 -1.281807 -1.702303  0.509432
 20210107 -0.334059  1.046615  0.400066 -0.733106
 20210108 -1.827526 -1.012644 -0.172205  0.505848
 20210109 -0.335458 -0.317219 -1.183980  0.654655,
 'ret_prev':                SPY       TLT       VXX       QQQ
 20210105  1.194871  0.434920 -0.020087 -0.463653
 20210106  1.259615 -0.289548  1.298278  2.414164
 20210107  0.825667 -1.320791 -1.237942  0.404561
 20210108 -1.418658  0.240768 -0.755033  0.416537
 20210109 -0.796261 -0.260931  0.477129  0.348025,
 'pe':                SPY       TLT       VXX       QQQ
 20210105 -0.207814 -0.970921  0.643785  0.113942
 20210106  0.013770 -1.006029  1.360488  0.376946
 20210107  0.807295  0.336137  1.353254 -0.067273
 20210108 -0.590600 -1.808742 -1.213458 -1.056192
 20210109  1.072926  1.209638 -0.264925 -1.300229,
 'analyst_est':                SPY       TLT       VXX       QQQ
 20210105  1.735306 -0.853299 -0.827084  0.570449
 20210106 -0.629966  0.765116  1.383105  1.018146
 20210107 -1.523721 -0.591616 -0.060504  0.067806
 20210108 -0.072663  0.638598  1.381048  1.138828
 20210109  0.760623 -0.471269  1.020712  0.150290}

In [6]:
multi = pd.concat(data)
multi

                           SPY       TLT       VXX       QQQ
earnings    20210105  1.202382  0.388800 -1.921227 -0.897985
            20210106 -0.896041 -1.281807 -1.702303  0.509432
            20210107 -0.334059  1.046615  0.400066 -0.733106
            20210108 -1.827526 -1.012644 -0.172205  0.505848
            20210109 -0.335458 -0.317219 -1.183980  0.654655
ret_prev    20210105  1.194871  0.434920 -0.020087 -0.463653
            20210106  1.259615 -0.289548  1.298278  2.414164
            20210107  0.825667 -1.320791 -1.237942  0.404561
            20210108 -1.418658  0.240768 -0.755033  0.416537
            20210109 -0.796261 -0.260931  0.477129  0.348025
pe          20210105 -0.207814 -0.970921  0.643785  0.113942
            20210106  0.013770 -1.006029  1.360488  0.376946
            20210107  0.807295  0.336137  1.353254 -0.067273
            20210108 -0.590600 -1.808742 -1.213458 -1.056192
            20210109  1.072926  1.209638 -0.264925 -1.300229
analyst_est 20210105  1.735306 -0.853299 -0.827084  0.570449
            20210106 -0.629966  0.765116  1.383105  1.018146
            20210107 -1.523721 -0.591616 -0.060504  0.067806
            20210108 -0.072663  0.638598  1.381048  1.138828
            20210109  0.760623 -0.471269  1.020712  0.150290

In [7]:
multi.loc['pe']

               SPY       TLT       VXX       QQQ
20210105 -0.207814 -0.970921  0.643785  0.113942
20210106  0.013770 -1.006029  1.360488  0.376946
20210107  0.807295  0.336137  1.353254 -0.067273
20210108 -0.590600 -1.808742 -1.213458 -1.056192
20210109  1.072926  1.209638 -0.264925 -1.300229

In [8]:
# For key and specific column.  mult.loc['key label', 'column name']
multi.loc['pe', 'SPY']

20210105   -0.207814
20210106    0.013770
20210107    0.807295
20210108   -0.590600
20210109    1.072926
Name: SPY, dtype: float64

In [9]:
# slicing
multi.loc['ret_prev':'analyst_est'] # includes ret_prev, pe, and analyst_est

                           SPY       TLT       VXX       QQQ
ret_prev    20210105  1.194871  0.434920 -0.020087 -0.463653
            20210106  1.259615 -0.289548  1.298278  2.414164
            20210107  0.825667 -1.320791 -1.237942  0.404561
            20210108 -1.418658  0.240768 -0.755033  0.416537
            20210109 -0.796261 -0.260931  0.477129  0.348025
pe          20210105 -0.207814 -0.970921  0.643785  0.113942
            20210106  0.013770 -1.006029  1.360488  0.376946
            20210107  0.807295  0.336137  1.353254 -0.067273
            20210108 -0.590600 -1.808742 -1.213458 -1.056192
            20210109  1.072926  1.209638 -0.264925 -1.300229
analyst_est 20210105  1.735306 -0.853299 -0.827084  0.570449
            20210106 -0.629966  0.765116  1.383105  1.018146
            20210107 -1.523721 -0.591616 -0.060504  0.067806
            20210108 -0.072663  0.638598  1.381048  1.138828
            20210109  0.760623 -0.471269  1.020712  0.150290

## Understanding `.loc` with a MultiIndex DataFrame

This DataFrame was created using `pd.concat(data)`, which results in a **MultiIndex**:

- **Level 0 (outer index):** data type (e.g., `'earnings'`, `'ret_prev'`, `'pe'`, `'analyst_est'`)
- **Level 1 (inner index):** dates (e.g., `'20210107'`)

Each row is identified by a tuple:
`('ret_prev', '20210107')`

---

### Command Breakdown (following cell)

`multi.loc[('ret_prev','20210107'), ['SPY','TLT']]`

#### 1. `.loc`
- Label-based indexing (uses index names, not positions)

#### 2. Row Selection
`('ret_prev','20210107')`

- Selects the row where:
  - Level 0 = `'ret_prev'`
  - Level 1 = `'20210107'`

#### 3. Column Selection
`['SPY','TLT']`

- Selects only these two columns from that row

---

### Result

Returns the values for SPY and TLT for `'ret_prev'` on `'20210107'`:

```
SPY    1.262910
TLT    0.941813
```

---

### Key Takeaways

- `.loc` uses **labels**, not positions
- MultiIndex rows require a **tuple**: `(level_0, level_1)`
- Columns are selected like a normal list

In [10]:
# multi.loc[('ret_prev','20210107'), ['SPY','TLT']]
#
# Explanation:
# This DataFrame uses a MultiIndex created by pd.concat(data), where:
#   - Level 0 index = data type (e.g., 'earnings', 'ret_prev', etc.)
#   - Level 1 index = date (e.g., '20210107')
#
# ('ret_prev','20210107') is a tuple that selects a specific row:
#   - 'ret_prev' → first index level
#   - '20210107' → second index level
#
# ['SPY','TLT'] selects only those columns from that row
#
# Result:
# Returns the SPY and TLT values for 'ret_prev' on '20210107'
#
# Key idea:
#   - .loc = label-based indexing
#   - MultiIndex requires tuple-based row selection

multi.loc[('ret_prev','20210107'),['SPY','TLT']]

SPY    0.825667
TLT   -1.320791
Name: (ret_prev, 20210107), dtype: float64

### Selecting a Single Column from a MultiIndex DataFrame

```python
ser = multi['SPY']
```

---

### What This Does

- `multi` is a **DataFrame** with multiple columns (SPY, TLT, VXX, QQQ)
- Selecting a single column (`'SPY'`) returns a **Series**

#### Why a Series?
- A **DataFrame** is 2-dimensional (rows + columns)
- A **Series** is 1-dimensional (a single column of data)

So:
```python
multi['SPY']
```
returns a **Series** because only one column is selected.

---

### What the Result Looks Like

The resulting `ser` still keeps the **MultiIndex**:

```
earnings      20210105    0.8747
              20210106    0.5045
...
ret_prev      20210107    1.2629
...
pe            20210108    1.1127
...
analyst_est   20210109    2.6261
```

- Index = `(category, date)`
- Values = SPY data

---

### Purpose of Creating a Series

#### 1. Focus on a Single Variable
Instead of working with all columns:
```python
multi
```

You isolate one:
```python
ser
```

---

#### 2. Easier MultiIndex Slicing

```python
ser.loc['ret_prev']
```

Returns:
```
20210105   -0.6496
20210106    0.6976
20210107    1.2629
...
```

---

#### 3. Useful for Analysis and Modeling

Working with a Series makes it easier to:
- Compute statistics (`mean`, `std`)
- Apply transformations (`pct_change`, rolling averages)
- Use as input for models

Example:
```python
ser.mean()
ser.std()
ser.pct_change()
```

---

#### 4. Cleaner Data Manipulation

A Series simplifies operations compared to handling multiple columns at once.

---

### Important Detail

```python
multi['SPY']     # returns a Series
multi[['SPY']]   # returns a DataFrame
```

- Single brackets → Series
- Double brackets → DataFrame

---

### Key Takeaways

- Selecting one column returns a **Series**
- The **MultiIndex is preserved**
- Series are easier to work with for analysis and modeling

In [11]:
ser = multi['SPY']
ser

earnings     20210105    1.202382
             20210106   -0.896041
             20210107   -0.334059
             20210108   -1.827526
             20210109   -0.335458
ret_prev     20210105    1.194871
             20210106    1.259615
             20210107    0.825667
             20210108   -1.418658
             20210109   -0.796261
pe           20210105   -0.207814
             20210106    0.013770
             20210107    0.807295
             20210108   -0.590600
             20210109    1.072926
analyst_est  20210105    1.735306
             20210106   -0.629966
             20210107   -1.523721
             20210108   -0.072663
             20210109    0.760623
Name: SPY, dtype: float64

In [12]:
# Working with the Series.  Pass in the key label, the output are the inner key and values.
ser['pe']

20210105   -0.207814
20210106    0.013770
20210107    0.807295
20210108   -0.590600
20210109    1.072926
Name: SPY, dtype: float64

## Below is an example of working with a DataFrame from a MultiIndex DataFrame

In [13]:
df_spy = multi[['SPY']]
df_spy

                           SPY
earnings    20210105  1.202382
            20210106 -0.896041
            20210107 -0.334059
            20210108 -1.827526
            20210109 -0.335458
ret_prev    20210105  1.194871
            20210106  1.259615
            20210107  0.825667
            20210108 -1.418658
            20210109 -0.796261
pe          20210105 -0.207814
            20210106  0.013770
            20210107  0.807295
            20210108 -0.590600
            20210109  1.072926
analyst_est 20210105  1.735306
            20210106 -0.629966
            20210107 -1.523721
            20210108 -0.072663
            20210109  0.760623

### Understanding `ser.unstack(level=0)`

```python
ser.unstack(level=0)
```

---

### What Was Passed

- `ser` is a **Pandas Series**
- It has a **MultiIndex** with two levels:
  - **Level 0:** category (e.g., `'earnings'`, `'ret_prev'`, `'pe'`, `'analyst_est'`)
  - **Level 1:** date (e.g., `'20210107'`)

---

### What `unstack(level=0)` Does

- Moves **Level 0 of the index** into **columns**
- Converts the Series into a **DataFrame**

#### Concept:
```
(category, date) → value
```

becomes:

```
date → columns (category)
```

---

### Before vs After

#### Before (Series)
```
earnings    20210105    0.87
ret_prev    20210105   -0.64
pe          20210105   -0.08
...
```

#### After (`unstack(level=0)`)
```
            earnings   ret_prev   pe   analyst_est
20210105     0.87      -0.64    -0.08    ...
20210106     ...
```

- **Index:** dates
- **Columns:** categories

---

### Why This Is Useful

- Converts data into a **tabular format**
- Ideal for:
  - Time series analysis
  - Feature engineering
  - Plotting
  - Machine learning inputs

---

### Other Options You Could Use

#### 1. Unstack a Different Level
```python
ser.unstack(level=1)
```
- Moves **dates into columns**
- Rows become categories

---

#### 2. Use Level Name Instead of Number
```python
ser.unstack(level='category')
```
- Same as `level=0`, but clearer

---

#### 3. Default Behavior
```python
ser.unstack()
```
- Defaults to the **last level** (`level=-1`)
- Equivalent to `level=1` in this case

---

#### 4. Fill Missing Values
```python
ser.unstack(level=0, fill_value=0)
```
- Replaces missing combinations with a value instead of NaN

---

#### 5. Multiple Levels (Advanced)
```python
ser.unstack(level=[0, 1])
```
- Used when there are more than two index levels

---

### Important Constraint

- Each index combination must map to **one value**
- If duplicates exist, Pandas will raise an error:
```
ValueError: Index contains duplicate entries
```

---

### Key Takeaways

- `unstack` moves an index level into columns
- `level=0` → first index level becomes columns
- Converts a **Series → DataFrame**
- Useful for reshaping data into analysis-ready format

In [14]:
# unstack a multindex series into a dataframe
ser.unstack(level=0)

          earnings  ret_prev        pe  analyst_est
20210105  1.202382  1.194871 -0.207814     1.735306
20210106 -0.896041  1.259615  0.013770    -0.629966
20210107 -0.334059  0.825667  0.807295    -1.523721
20210108 -1.827526 -1.418658 -0.590600    -0.072663
20210109 -0.335458 -0.796261  1.072926     0.760623

In [15]:
ser_level1 = ser.unstack(level=1)
ser_level1

             20210105  20210106  20210107  20210108  20210109
earnings     1.202382 -0.896041 -0.334059 -1.827526 -0.335458
ret_prev     1.194871  1.259615  0.825667 -1.418658 -0.796261
pe          -0.207814  0.013770  0.807295 -0.590600  1.072926
analyst_est  1.735306 -0.629966 -1.523721 -0.072663  0.760623

### Understanding `ser.unstack(level=0).stack()`

```python
ser.unstack(level=0).stack()
```

---

### What This Does

This is a **reshape → reshape back** operation:

1. `unstack(level=0)` converts part of the index into columns
2. `stack()` converts those columns back into the index

---

### Step 1: `unstack(level=0)`

- Moves **Level 0 (category)** into **columns**
- Converts the Series into a DataFrame

#### Before (Series)
```
(category, date) → value
```

#### After (DataFrame)
```
date → columns (category)
```

---

### Step 2: `.stack()`

- Moves **columns back into the index**
- Converts the DataFrame back into a Series

#### Result
```
(category, date) → value
```

---

### Final Outcome

- Returns a Series that **looks like the original**
- Often identical, but not always

---

### Important Caveats

#### 1. Missing Values (NaN)

- `unstack()` introduces `NaN` for missing combinations
- `stack()` **drops NaN values by default**

This means data can be lost during the round trip

---

#### 2. Index Ordering

- The order of index levels or values may change

---

### Safe Round Trip

To preserve all data:

```python
ser.unstack(level=0).stack(dropna=False)
```

---

### Why This Is Useful

#### 1. Reshaping for Analysis

```python
df = ser.unstack(level=0)
# perform analysis or transformations
ser_clean = df.stack()
```

---

#### 2. Data Cleaning

- `unstack()` exposes missing data
- `stack()` can remove incomplete rows

---

#### 3. Structure Normalization

- Helps enforce consistent MultiIndex structure

---

### Mental Model

- `unstack` → index → columns
- `stack` → columns → index

So this operation is:

```
index → columns → index
```

---

### Key Takeaways

- This is a **round-trip reshape**
- It often returns the original Series
- It may:
  - drop missing values
  - change ordering
- Useful for **reshaping and cleaning data**

In [16]:
ser.unstack(level=0).stack()

20210105  earnings       1.202382
          ret_prev       1.194871
          pe            -0.207814
          analyst_est    1.735306
20210106  earnings      -0.896041
          ret_prev       1.259615
          pe             0.013770
          analyst_est   -0.629966
20210107  earnings      -0.334059
          ret_prev       0.825667
          pe             0.807295
          analyst_est   -1.523721
20210108  earnings      -1.827526
          ret_prev      -1.418658
          pe            -0.590600
          analyst_est   -0.072663
20210109  earnings      -0.335458
          ret_prev      -0.796261
          pe             1.072926
          analyst_est    0.760623
dtype: float64

### Understanding `pd.concat(data, axis=1)`

```python
multi = pd.concat(data, axis=1)
```

---

### What This Does

- Combines multiple DataFrames stored in `data`
- Concatenates them **horizontally (side-by-side)**

---

### Key Parameter

- `axis=1` → concatenate along **columns**

| Axis | Meaning |
|------|--------|
| `axis=0` (default) | Stack vertically (add rows) |
| `axis=1` | Stack horizontally (add columns) |

---

### Input

- `data` is typically a **dictionary of DataFrames**

Example:
```python
{
    'earnings': df1,
    'ret_prev': df2,
    'pe': df3
}
```

---

### Output

- A single **DataFrame**
- Columns become a **MultiIndex**

Example structure:

```
        earnings        ret_prev        pe
           SPY   TLT      SPY   TLT   SPY   TLT
date
20210105   ...   ...      ...   ...   ...   ...
```

---

### When to Use

- Combine multiple datasets with the **same index**
- Build feature tables (common in data science / ML)
- Align data from different sources side-by-side

---

### Key Takeaways

- `pd.concat(..., axis=1)` = horizontal merge
- Produces a **MultiIndex on columns**
- Requires keyword arguments in modern Pandas

In [18]:
multi = pd.concat(data,axis=1)

In [19]:
multi

          earnings                                ret_prev            \
               SPY       TLT       VXX       QQQ       SPY       TLT
20210105  1.202382  0.388800 -1.921227 -0.897985  1.194871  0.434920
20210106 -0.896041 -1.281807 -1.702303  0.509432  1.259615 -0.289548
20210107 -0.334059  1.046615  0.400066 -0.733106  0.825667 -1.320791
20210108 -1.827526 -1.012644 -0.172205  0.505848 -1.418658  0.240768
20210109 -0.335458 -0.317219 -1.183980  0.654655 -0.796261 -0.260931

                                    pe                                \
               VXX       QQQ       SPY       TLT       VXX       QQQ
20210105 -0.020087 -0.463653 -0.207814 -0.970921  0.643785  0.113942
20210106  1.298278  2.414164  0.013770 -1.006029  1.360488  0.376946
20210107 -1.237942  0.404561  0.807295  0.336137  1.353254 -0.067273
20210108 -0.755033  0.416537 -0.590600 -1.808742 -1.213458 -1.056192
20210109  0.477129  0.348025  1.072926  1.209638 -0.264925 -1.300229

         analyst_est
                 SPY       TLT       VXX       QQQ
20210105    1.735306 -0.853299 -0.827084  0.570449
20210106   -0.629966  0.765116  1.383105  1.018146
20210107   -1.523721 -0.591616 -0.060504  0.067806
20210108   -0.072663  0.638598  1.381048  1.138828
20210109    0.760623 -0.471269  1.020712  0.150290

# Pandas Indexing: Single vs Double Brackets (MultiIndex Case)

## 🧠 The Confusion

Example:

    print(type(multi['pe']))
    print(type(multi[['pe']]))

Output:

    <class 'pandas.DataFrame'>
    <class 'pandas.DataFrame'>

Normally:
- df['col'] → Series
- df[['col']] → DataFrame

But here, both return a DataFrame.

---

## 🔥 Root Cause: MultiIndex Columns

Your DataFrame has hierarchical (MultiIndex) columns.

Conceptually, instead of:

    ['pe', 'earnings']

You actually have:

    ('pe', 'SPY')
    ('pe', 'TLT')
    ('earnings', 'SPY')
    ('earnings', 'TLT')

So columns are grouped by levels.

---

## 🧠 What Pandas Is Actually Doing

### Case 1:

    multi['pe']

Interpretation:
- Select all columns where level 0 == 'pe'

Result:
- Multiple columns returned
- Therefore → DataFrame

---

### Case 2:

    multi[['pe']]

Interpretation:
- Select a list of top-level groups

Result:
- Still multiple columns
- Therefore → DataFrame

---

## ⚠️ Why the Expectation Breaks

Assumption:

    multi['pe'] → one column → Series

Reality:

    multi['pe'] → multiple columns → DataFrame

Because:
- 'pe' is NOT a single column
- It is a label in a column level

---

## 🧠 Updated Mental Model

Normal DataFrame:

    columns = ['pe', 'earnings']

→ 'pe' returns a Series

MultiIndex DataFrame:

    columns = [
        ('pe', 'SPY'),
        ('pe', 'TLT'),
        ...
    ]

→ 'pe' returns multiple columns → DataFrame

---

## 🛠️ How to Get a Series

You must fully specify the column:

    multi[('pe', 'SPY')]

or:

    multi['pe']['SPY']

Now:
- One column selected
- → Series

---

## ⚡ Alternative (Explicit Level Selection)

    multi.xs('pe', axis=1, level=0)

- Selects all 'pe' columns
- Returns DataFrame (still multiple columns)

---

## 🧭 Final Rule

Do NOT rely on bracket syntax alone.

Instead:

- 1 column selected → Series
- Multiple columns selected → DataFrame

---

## 💡 Key Insight

With MultiIndex:
- Labels like 'pe' refer to groups, not individual columns
- Output type depends on how many columns are returned

In [20]:
# indexing
multi['pe']

               SPY       TLT       VXX       QQQ
20210105 -0.207814 -0.970921  0.643785  0.113942
20210106  0.013770 -1.006029  1.360488  0.376946
20210107  0.807295  0.336137  1.353254 -0.067273
20210108 -0.590600 -1.808742 -1.213458 -1.056192
20210109  1.072926  1.209638 -0.264925 -1.300229

In [21]:
multi[['pe','earnings']]

                pe                                earnings            \
               SPY       TLT       VXX       QQQ       SPY       TLT
20210105 -0.207814 -0.970921  0.643785  0.113942  1.202382  0.388800
20210106  0.013770 -1.006029  1.360488  0.376946 -0.896041 -1.281807
20210107  0.807295  0.336137  1.353254 -0.067273 -0.334059  1.046615
20210108 -0.590600 -1.808742 -1.213458 -1.056192 -1.827526 -1.012644
20210109  1.072926  1.209638 -0.264925 -1.300229 -0.335458 -0.317219


               VXX       QQQ
20210105 -1.921227 -0.897985
20210106 -1.702303  0.509432
20210107  0.400066 -0.733106
20210108 -0.172205  0.505848
20210109 -1.183980  0.654655

In [23]:
print('multi[pe]:', type(multi['pe']))     # Series
print('multi[[pe]]:', type(multi[['pe']]))   # DataFrame

multi[pe]: <class 'pandas.DataFrame'>
multi[[pe]]: <class 'pandas.DataFrame'>

In [28]:
Selena = multi[('pe', 'SPY')]
Selena

20210105   -0.207814
20210106    0.013770
20210107    0.807295
20210108   -0.590600
20210109    1.072926
Name: (pe, SPY), dtype: float64

In [29]:
type(Selena)

pandas.Series

# Rearranging Axes

# Pandas MultiIndex: `swaplevel` vs `swaplevel().sort_index()`

## 🧠 Overview

Two similar-looking operations:

    multi.swaplevel(0, 1, axis=1)

and

    multi.swaplevel(0, 1, axis=1).sort_index(axis=1)

They produce **different usability outcomes**, even though both run successfully.

---

## 🔄 What `swaplevel` Does

    multi.swaplevel(0, 1, axis=1)

- Swaps levels in a MultiIndex (here, column levels 0 and 1)
- Changes the **hierarchical structure**, but **NOT the order**

### Example (Before)

    ('pe', 'SPY')
    ('pe', 'TLT')
    ('earnings', 'SPY')
    ('earnings', 'TLT')

### After `swaplevel`

    ('SPY', 'pe')
    ('TLT', 'pe')
    ('SPY', 'earnings')
    ('TLT', 'earnings')

---

## ⚠️ Problem After `swaplevel`

- Columns are now **out of order**
- Not grouped logically
- Harder to read and work with

Example:

    ('SPY', 'pe')
    ('TLT', 'pe')
    ('SPY', 'earnings')
    ('TLT', 'earnings')

This is valid, but messy.

---

## 🔽 What `sort_index` Fixes

    multi.swaplevel(0, 1, axis=1).sort_index(axis=1)

- Sorts columns after swapping
- Restores logical grouping

### Result:

    ('SPY', 'earnings')
    ('SPY', 'pe')
    ('TLT', 'earnings')
    ('TLT', 'pe')

---

## 🧪 Comparison

### Without Sorting

    multi.swaplevel(0, 1, axis=1)

- Structure changed ✔
- Order messy ❌

---

### With Sorting

    multi.swaplevel(0, 1, axis=1).sort_index(axis=1)

- Structure changed ✔
- Order clean ✔

---

## 🧠 Why Pandas Doesn’t Auto-Sort

Pandas assumes you may want to preserve original ordering.

So it:
- Changes structure
- Leaves ordering alone

---

## ⚡ Practical Impact

Without sorting:
- Column grouping is inconsistent
- Selection becomes confusing
- Harder to reason about structure

With sorting:
- Columns are grouped logically
- Easier to select and analyze data

---

## 🧭 Key Takeaway

- `swaplevel` → changes hierarchy
- `sort_index(axis=1)` → restores order

---

## 💡 Mental Model

Think of it like reorganizing a toolbox:

- `swaplevel` → dump tools into new drawers
- `sort_index` → actually organize them so you can find things again

In [30]:
# rearrange axes
multi.swaplevel(0,1,1)

,SPY,TLT,VXX,QQQ,SPY,TLT,VXX,QQQ,SPY,TLT,VXX,QQQ,SPY,TLT,VXX,QQQ
,earnings,earnings,earnings,earnings,ret_prev,ret_prev,ret_prev,ret_prev,pe,pe,pe,pe,analyst_est,analyst_est,analyst_est,analyst_est
20210105,1.202382,0.388800,-1.921227,-0.897985,1.194871,0.434920,-0.020087,-0.463653,-0.207814,-0.970921,0.643785,0.113942,1.735306,-0.853299,-0.827084,0.570449
20210106,-0.896041,-1.281807,-1.702303,0.509432,1.259615,-0.289548,1.298278,2.414164,0.013770,-1.006029,1.360488,0.376946,-0.629966,0.765116,1.383105,1.018146
20210107,-0.334059,1.046615,0.400066,-0.733106,0.825667,-1.320791,-1.237942,0.404561,0.807295,0.336137,1.353254,-0.067273,-1.523721,-0.591616,-0.060504,0.067806
20210108,-1.827526,-1.012644,-0.172205,0.505848,-1.418658,0.240768,-0.755033,0.416537,-0.590600,-1.808742,-1.213458,-1.056192,-0.072663,0.638598,1.381048,1.138828
20210109,-0.335458,-0.317219,-1.183980,0.654655,-0.796261,-0.260931,0.477129,0.348025,1.072926,1.209638,-0.264925,-1.300229,0.760623,-0.471269,1.020712,0.150290

In [32]:
multi.swaplevel(0,1,1).sort_index(axis=1)

                 QQQ                                       SPY            \
         analyst_est  earnings        pe  ret_prev analyst_est  earnings
20210105    0.570449 -0.897985  0.113942 -0.463653    1.735306  1.202382
20210106    1.018146  0.509432  0.376946  2.414164   -0.629966 -0.896041
20210107    0.067806 -0.733106 -0.067273  0.404561   -1.523721 -0.334059
20210108    1.138828  0.505848 -1.056192  0.416537   -0.072663 -1.827526
20210109    0.150290  0.654655 -1.300229  0.348025    0.760623 -0.335458

                                     TLT                                \
                pe  ret_prev analyst_est  earnings        pe  ret_prev
20210105 -0.207814  1.194871   -0.853299  0.388800 -0.970921  0.434920
20210106  0.013770  1.259615    0.765116 -1.281807 -1.006029 -0.289548
20210107  0.807295  0.825667   -0.591616  1.046615  0.336137 -1.320791
20210108 -0.590600 -1.418658    0.638598 -1.012644 -1.808742  0.240768
20210109  1.072926 -0.796261   -0.471269 -0.317219  1.209638 -0.260931

                 VXX
         analyst_est  earnings        pe  ret_prev
20210105   -0.827084 -1.921227  0.643785 -0.020087
20210106    1.383105 -1.702303  1.360488  1.298278
20210107   -0.060504  0.400066  1.353254 -1.237942
20210108    1.381048 -0.172205 -1.213458 -0.755033
20210109    1.020712 -1.183980 -0.264925  0.477129

# Pandas MultiIndex Aggregation Across Columns

## 🧠 Goal

Sum values across columns that share the same level in a MultiIndex.

---

## 🔧 Command

    multi.T.groupby(level=0).sum().T

---

## 🧠 What It Does

This operation groups columns by a specified level and sums values across those groups.

---

## 🔍 Step-by-Step Breakdown

### 1. Transpose the DataFrame

    multi.T

- Converts columns into rows
- MultiIndex columns become a MultiIndex index

---

### 2. Group by Level

    .groupby(level=0)

- Groups data based on level 0 of the index (original column level)
- Each group represents columns that shared the same top-level label

---

### 3. Aggregate

    .sum()

- Sums values within each group
- Reduces multiple entries into a single aggregated value per group

---

### 4. Transpose Back

    .T

- Restores original orientation
- Grouped results are now back in column form

---

## 🧪 Example Concept

Original column structure:

    ('pe', 'SPY')
    ('pe', 'TLT')
    ('earnings', 'SPY')
    ('earnings', 'TLT')

After operation:

    pe         → sum of all 'pe' columns
    earnings   → sum of all 'earnings' columns

---

## 🧭 Result

- Columns are grouped by level 0
- Values are aggregated across each group
- Output is a cleaner, reduced DataFrame

---

## 💡 Key Idea

To aggregate across MultiIndex columns:
- Temporarily treat columns as rows
- Perform grouping and aggregation
- Restore original structure

In [35]:
# sum across an axis
multi.T.groupby(level=0).sum().T

          analyst_est  earnings        pe  ret_prev
20210105     0.625372 -1.228029 -0.421008  1.146052
20210106     2.536401 -3.370719  0.745176  4.682509
20210107    -2.108034  0.379516  2.429413 -1.328505
20210108     3.085812 -2.506527 -4.668992 -1.516386
20210109     1.460355 -1.182002  0.717410 -0.232037

In [36]:
# standard pandas functions produce multi-index series
multi.mean()

earnings     SPY   -0.438140
             TLT   -0.235251
             VXX   -0.915930
             QQQ    0.007769
ret_prev     SPY    0.213047
             TLT   -0.239116
             VXX   -0.047531
             QQQ    0.623927
pe           SPY    0.219116
             TLT   -0.447983
             VXX    0.375829
             QQQ   -0.386561
analyst_est  SPY    0.053916
             TLT   -0.102494
             VXX    0.579455
             QQQ    0.589104
dtype: float64

In [38]:
type(multi.mean())

pandas.Series

In [41]:
multi.mean().unstack(level=1)

                  SPY       TLT       VXX       QQQ
earnings    -0.438140 -0.235251 -0.915930  0.007769
ret_prev     0.213047 -0.239116 -0.047531  0.623927
pe           0.219116 -0.447983  0.375829 -0.386561
analyst_est  0.053916 -0.102494  0.579455  0.589104

In [42]:
type(multi.mean().unstack(level=1))

pandas.DataFrame