# Groupby, Pivot, Merge

In [1]:
import pandas as pd 
import numpy as np 

univ = ['AAPL','MSFT','BAC','GS']
dates = pd.date_range('20110101','20201231')
df = pd.DataFrame(np.random.randn(len(dates),len(univ)),index=dates,columns=univ)
df

                AAPL      MSFT       BAC        GS
2011-01-01  1.520429  1.447135 -0.157266  0.978755
2011-01-02 -0.240267  1.479742 -0.537518 -0.112783
2011-01-03  0.459333  0.107961 -0.211853  0.543682
2011-01-04  0.214619  1.011449  1.950263  0.874949
2011-01-05  0.202895  0.086989 -0.264394 -0.239951
...              ...       ...       ...       ...
2020-12-27  0.457880 -1.242520 -0.874413  1.545443
2020-12-28 -0.070364 -0.156876 -0.402209 -2.242678
2020-12-29 -0.192440 -0.179836 -0.006434 -0.289394
2020-12-30 -2.089112 -0.559439  0.767413  1.112193
2020-12-31  0.698724  0.673288  1.085240 -2.173544

[3653 rows x 4 columns]

In [2]:
sector = {'AAPL':'Tech','MSFT':'Tech','BAC':'Fin','GS':'Fin'}
data=[]
for dt in dates:
    for x in univ:
        data.append([x,sector[x],dt,np.random.randn(),np.random.randn()])
data = pd.DataFrame(data,columns=['ticker','sector','date','signal1','signal2'])
data

      ticker sector       date   signal1   signal2
0       AAPL   Tech 2011-01-01  0.283229  3.056726
1       MSFT   Tech 2011-01-01  0.144383  0.326354
2        BAC    Fin 2011-01-01  1.009180  1.956001
3         GS    Fin 2011-01-01  0.424052  1.580517
4       AAPL   Tech 2011-01-02  0.035900  1.173141
...      ...    ...        ...       ...       ...
14607     GS    Fin 2020-12-30  0.174601 -0.541720
14608   AAPL   Tech 2020-12-31 -0.679130  0.258643
14609   MSFT   Tech 2020-12-31 -0.678390 -0.853023
14610    BAC    Fin 2020-12-31 -0.211526 -2.135673
14611     GS    Fin 2020-12-31 -0.109001 -0.065435

[14612 rows x 5 columns]

## Groupby

In [7]:
# whats the average signal of each ticker?
data.groupby(['ticker', 'signal1', 'signal2']).mean(numeric_only=True)

Empty DataFrame
Columns: []
Index: [(AAPL, -3.789365449635688, -0.03045119942956217), (AAPL, -3.356975175280984, 2.026448983188908), (AAPL, -3.285931352726751, -0.04763283263615578), (AAPL, -3.261226252863009, 1.5452533860659672), (AAPL, -3.1582259351240873, -0.8695598489878148), (AAPL, -3.140618792425284, 0.48201475307091574), (AAPL, -3.093163445879957, 0.7753036295652878), (AAPL, -2.949139483060701, -1.291682792534341), (AAPL, -2.942985992143235, -1.1975276533297503), (AAPL, -2.925216553916142, 0.5117955600269964), (AAPL, -2.848101375149535, 1.806858665323608), (AAPL, -2.8179319877274325, 0.5959814942079392), (AAPL, -2.7619932246964103, -0.28950684246034464), (AAPL, -2.7618439077745487, 0.2594917365496343), (AAPL, -2.671630451326498, -2.0999101758584557), (AAPL, -2.6034543086607034, -1.0963522468513065), (AAPL, -2.601448951518862, -0.29757387826118903), (AAPL, -2.594506780487217, 1.2668565848883173), (AAPL, -2.589922801052292, 0.849103244260725), (AAPL, -2.5527159262325028, 0.3108253472554434), (AAPL, -2.5030259853411936, 1.2714303764547086), (AAPL, -2.4780972238561114, -0.5479472280462754), (AAPL, -2.462645912260916, 1.3552375178469844), (AAPL, -2.4530289257481943, 1.2313169373475945), (AAPL, -2.443508157697296, -0.4020298988634882), (AAPL, -2.4425782499494253, -0.1767538970864223), (AAPL, -2.435948825801942, -1.8606827184763897), (AAPL, -2.428849926785643, 0.4772569682566772), (AAPL, -2.4218040683201183, -0.3648479057910269), (AAPL, -2.417357172680807, -1.0892106567966258), (AAPL, -2.4092456594018343, -0.20230459158543126), (AAPL, -2.393469506070596, -1.8371001684021413), (AAPL, -2.391640915888166, 0.48125229623279087), (AAPL, -2.3880395054571153, -1.4208874917303451), (AAPL, -2.3627786108041358, 0.2064972055387908), (AAPL, -2.3456331923188474, -1.2611966723324937), (AAPL, -2.336710240038195, -0.2630543574999656), (AAPL, -2.3324053662597892, -1.2463857118830273), (AAPL, -2.324083979107854, -0.9471302176929932), (AAPL, -2.3048706644633863, -0.6295262597663269), (AAPL, -2.2845397228781117, 0.17870806817203527), (AAPL, -2.282219176422321, 0.025014641786916418), (AAPL, -2.2801469712705686, -0.5069520779872453), (AAPL, -2.2787918493003883, 0.6390368945104316), (AAPL, -2.271015129120401, -1.0515319015427382), (AAPL, -2.2626885677217645, 0.8848726271195656), (AAPL, -2.254693923957576, 0.9575322236609741), (AAPL, -2.244862698570458, 0.8114914322598668), (AAPL, -2.241993561464542, 0.7945828981191464), (AAPL, -2.231086187833203, 1.3809824399306703), (AAPL, -2.2241595706857713, -1.1433482721012511), (AAPL, -2.213710592152655, -0.4564236383703374), (AAPL, -2.2112079918038576, 2.1541343518140166), (AAPL, -2.209284496333789, -0.28618692163272674), (AAPL, -2.2021297412745, -0.36148595169976144), (AAPL, -2.200970917498837, -0.19604101293906723), (AAPL, -2.186683947051441, -0.057498567335086154), (AAPL, -2.1814033719354136, 0.2519923909397288), (AAPL, -2.180766378107872, 0.9791473568672425), (AAPL, -2.178985080377871, 0.34158565265236446), (AAPL, -2.1786872645279622, -0.963201149461), (AAPL, -2.177074911789436, -0.573988702948513), (AAPL, -2.1656810962934845, 0.02007535952728657), (AAPL, -2.161807895236673, 0.24895685521002783), (AAPL, -2.1602616478451115, -0.17858906127461047), (AAPL, -2.1498747849140694, -0.3011891569093703), (AAPL, -2.132493996931324, 0.38715291972963406), (AAPL, -2.1302445901112717, -0.2683853676678084), (AAPL, -2.1217884785152155, -1.731863280007557), (AAPL, -2.1180082996413434, -0.8805913754165111), (AAPL, -2.1067916225803947, 0.6606222290477555), (AAPL, -2.0981259363252334, -0.36480536842632677), (AAPL, -2.0977819746579858, 0.47947337455068934), (AAPL, -2.0953435103065168, 1.033891699922278), (AAPL, -2.084899293057913, -0.9799185333463403), (AAPL, -2.0765807705909123, -0.8277616169647127), (AAPL, -2.0754250790952815, -0.18568434893003957), (AAPL, -2.0684794505474122, 1.660074211199303), (AAPL, -2.04638317087636, -1.1273312318094495), (AAPL, -2.034147164678289, 1.3678228509626698), (AAPL, -2.033286549726127, -0.17722522899317666), (AAPL, -2.022957657463184, 1.0879496226095826), (AAPL, -2.019380145898667, -0.32400128712871795), (AAPL, -2.0090492537843416, 1.6041681213747208), (AAPL, -1.9837956066274074, -1.1422886658140685), (AAPL, -1.9815488111012243, -0.31471533151657965), (AAPL, -1.9663068557989716, -1.3182650339011446), (AAPL, -1.9627327937991002, 0.6157500427392675), (AAPL, -1.960773660443606, -0.3272302554111874), (AAPL, -1.9354865099212635, -2.5742972414714655), (AAPL, -1.9272307137098097, 0.6203964628956697), (AAPL, -1.9241224040382992, 0.2838667083630589), (AAPL, -1.921541796474387, -0.7158942655091833), (AAPL, -1.9211470709126266, -0.3363541982036285), (AAPL, -1.9203970182121894, -0.2124064407466916), (AAPL, -1.9087420056783082, 0.6388198439980924), (AAPL, -1.906780373653538, 0.4439351971477997), (AAPL, -1.906173766861563, -0.6159198253026865), (AAPL, -1.9000823528472608, -0.6334721041788777), (AAPL, -1.8945452326456478, 0.502572483118138), ...]

[14612 rows x 0 columns]

In [8]:
# whats the average signal of each sector on each day?
data.groupby(['sector','date']).mean(numeric_only=True)

                    signal1   signal2
sector date
Fin    2011-01-01  0.716616  1.768259
       2011-01-02 -1.890362 -0.108855
       2011-01-03  0.212871  0.416457
       2011-01-04 -0.782722 -0.063056
       2011-01-05  0.671981  0.268188
...                     ...       ...
Tech   2020-12-27 -0.859563 -1.411057
       2020-12-28  0.015901 -0.552329
       2020-12-29  0.276250 -0.332662
       2020-12-30  0.654204  0.175398
       2020-12-31 -0.678760 -0.297190

[7306 rows x 2 columns]

In [11]:
# can index before applying the function
data.groupby(['sector','date'])[['signal1']].mean(numeric_only=True)

                    signal1
sector date
Fin    2011-01-01  0.716616
       2011-01-02 -1.890362
       2011-01-03  0.212871
       2011-01-04 -0.782722
       2011-01-05  0.671981
...                     ...
Tech   2020-12-27 -0.859563
       2020-12-28  0.015901
       2020-12-29  0.276250
       2020-12-30  0.654204
       2020-12-31 -0.678760

[7306 rows x 1 columns]

# Pandas `.apply()` with `groupby`: Conceptual Summary

## 🧠 Core Idea

`.apply()` lets you run a **custom function** on each group in a `groupby` operation.

Unlike built-in methods (`mean`, `sum`, etc.), it gives you full control over the logic.

---

## 🔧 Example

    def max_minus_min(x):
        return x.max() - x.min()

    data.groupby(['sector','date'])[['signal1','signal2']].apply(max_minus_min)

---

## 🧠 What’s Happening

1. Data is split into groups based on:

       ('sector', 'date')

2. For each group:

       x = subset of the DataFrame

3. Your function runs on each group:

       x.max() - x.min()

4. Results are combined into a new DataFrame

---

## ⚡ When to Use `.apply()`

Use `.apply()` when:

- You need **custom logic** not available in built-in functions
- You want to operate on **entire groups**, not just columns
- You need flexibility beyond `.agg()` or `.transform()`

---

## ⚠️ Important Considerations

- Slower than built-in aggregations (`mean`, `sum`, etc.)
- Should not be your first choice if a built-in method exists
- Best used for **non-standard or complex operations**

---

## 🧭 Mental Model

Think of `groupby().apply()` as:

> "Split → Apply custom function → Combine results"

---

## 🔑 Key Insight

- `.agg()` → predefined, optimized operations
- `.transform()` → returns same shape as input
- `.apply()` → **maximum flexibility**, less performance

---

## 💡 Final Takeaway

`.apply()` is the “escape hatch” for group operations:

> Use it when Pandas doesn’t already give you the function you need

In [10]:
# use apply with groupby to pass an arbitrary function
def max_minus_min(x):
    return x.max()-x.min()

data.groupby(['sector','date'])[['signal1','signal2']].apply(max_minus_min

                    signal1   signal2
sector date
Fin    2011-01-01  0.585128  0.375484
       2011-01-02  0.848111  1.734540
       2011-01-03  1.923406  1.777767
       2011-01-04  2.088586  0.170600
       2011-01-05  0.442993  0.874202
...                     ...       ...
Tech   2020-12-27  1.060827  2.462820
       2020-12-28  0.941712  0.119097
       2020-12-29  0.735819  0.223701
       2020-12-30  1.473004  3.594782
       2020-12-31  0.000740  1.111665

[7306 rows x 2 columns]

In [13]:
# return a dataframe instead of a series
# the [[ 'text' ]] returns a dataframe
# the [ 'text' ] returns a series
def demean(x):
    return x - x.mean()

data.groupby(['sector','date'])[['signal1','signal2']].apply(demean)

                          signal1   signal2
sector date
Fin    2011-01-01 2      0.292564  0.187742
                  3     -0.292564 -0.187742
       2011-01-02 6      0.424055  0.867270
                  7     -0.424055 -0.867270
       2011-01-03 10    -0.961703 -0.888883
...                           ...       ...
Tech   2020-12-29 14601 -0.367909 -0.111851
       2020-12-30 14604  0.736502  1.797391
                  14605 -0.736502 -1.797391
       2020-12-31 14608 -0.000370  0.555833
                  14609  0.000370 -0.555833

[14612 rows x 2 columns]

In [9]:
df = data.groupby(['sector','date'])[['signal1','signal2']].mean()
df

                    signal1   signal2
sector date
Fin    2011-01-01 -0.203187 -0.065324
       2011-01-02 -1.006247  1.047700
       2011-01-03  1.052026  0.588958
       2011-01-04 -0.448476 -0.334251
       2011-01-05 -1.251335  0.432628
...                     ...       ...
Tech   2020-12-27 -0.709643  0.275530
       2020-12-28  0.244018  0.534283
       2020-12-29  0.005680  0.482225
       2020-12-30 -0.742111  0.633299
       2020-12-31 -0.483540 -1.213430

[7306 rows x 2 columns]

In [14]:
df.groupby(level=0).mean()

                AAPL      MSFT       BAC        GS
2011-01-01  1.520429  1.447135 -0.157266  0.978755
2011-01-02 -0.240267  1.479742 -0.537518 -0.112783
2011-01-03  0.459333  0.107961 -0.211853  0.543682
2011-01-04  0.214619  1.011449  1.950263  0.874949
2011-01-05  0.202895  0.086989 -0.264394 -0.239951
...              ...       ...       ...       ...
2020-12-27  0.457880 -1.242520 -0.874413  1.545443
2020-12-28 -0.070364 -0.156876 -0.402209 -2.242678
2020-12-29 -0.192440 -0.179836 -0.006434 -0.289394
2020-12-30 -2.089112 -0.559439  0.767413  1.112193
2020-12-31  0.698724  0.673288  1.085240 -2.173544

[3653 rows x 4 columns]

In [15]:
month = [x.month for x in data['date']]

In [17]:
data.groupby(month).mean(numeric_only=True)

     signal1   signal2
1   0.020137  0.021865
2  -0.031687 -0.041926
3   0.078626 -0.029075
4   0.002202  0.030336
5   0.002809 -0.033942
6  -0.000734 -0.020602
7  -0.015942  0.052253
8  -0.000860  0.013902
9  -0.017796  0.052094
10 -0.005868  0.012324
11  0.002628 -0.020182
12 -0.014361 -0.035675

In [18]:
for key,val in data.groupby('sector'):
    print (key)

Fin
Tech

In [19]:
# iterating in a groupby
for key,val in data.groupby('sector'):
    print (val)

      ticker sector       date   signal1   signal2
2        BAC    Fin 2011-01-01  1.009180  1.956001
3         GS    Fin 2011-01-01  0.424052  1.580517
6        BAC    Fin 2011-01-02 -1.466306  0.758415
7         GS    Fin 2011-01-02 -2.314417 -0.976125
10       BAC    Fin 2011-01-03 -0.748832 -0.472427
...      ...    ...        ...       ...       ...
14603     GS    Fin 2020-12-29 -0.742333  0.747767
14606    BAC    Fin 2020-12-30 -0.104745  0.656342
14607     GS    Fin 2020-12-30  0.174601 -0.541720
14610    BAC    Fin 2020-12-31 -0.211526 -2.135673
14611     GS    Fin 2020-12-31 -0.109001 -0.065435

[7306 rows x 5 columns]
      ticker sector       date   signal1   signal2
0       AAPL   Tech 2011-01-01  0.283229  3.056726
1       MSFT   Tech 2011-01-01  0.144383  0.326354
4       AAPL   Tech 2011-01-02  0.035900  1.173141
5       MSFT   Tech 2011-01-02  1.079511  0.377148
8       AAPL   Tech 2011-01-03  1.745756 -1.341330
...      ...    ...        ...       ...       ...
14601   MSFT   Tech 2020-12-29 -0.091659 -0.444512
14604   AAPL   Tech 2020-12-30  1.390706  1.972789
14605   MSFT   Tech 2020-12-30 -0.082298 -1.621993
14608   AAPL   Tech 2020-12-31 -0.679130  0.258643
14609   MSFT   Tech 2020-12-31 -0.678390 -0.853023

[7306 rows x 5 columns]

## Pivot

In [20]:
data

      ticker sector       date   signal1   signal2
0       AAPL   Tech 2011-01-01  0.283229  3.056726
1       MSFT   Tech 2011-01-01  0.144383  0.326354
2        BAC    Fin 2011-01-01  1.009180  1.956001
3         GS    Fin 2011-01-01  0.424052  1.580517
4       AAPL   Tech 2011-01-02  0.035900  1.173141
...      ...    ...        ...       ...       ...
14607     GS    Fin 2020-12-30  0.174601 -0.541720
14608   AAPL   Tech 2020-12-31 -0.679130  0.258643
14609   MSFT   Tech 2020-12-31 -0.678390 -0.853023
14610    BAC    Fin 2020-12-31 -0.211526 -2.135673
14611     GS    Fin 2020-12-31 -0.109001 -0.065435

[14612 rows x 5 columns]

In [21]:
# put Signal1 into a df with columns tickers and rows dates
df1 = data.set_index(['date','ticker'])['signal1'].unstack(level=1)
df1

ticker          AAPL       BAC        GS      MSFT
date
2011-01-01  0.283229  1.009180  0.424052  0.144383
2011-01-02  0.035900 -1.466306 -2.314417  1.079511
2011-01-03  1.745756 -0.748832  1.174574  0.361653
2011-01-04 -0.830788  0.261571 -1.827015 -0.316657
2011-01-05 -1.551993  0.450485  0.893478 -0.285942
...              ...       ...       ...       ...
2020-12-27 -0.329149 -0.985159 -0.240506 -1.389977
2020-12-28 -0.454955  1.879978 -0.260495  0.486757
2020-12-29  0.644160 -0.957661 -0.742333 -0.091659
2020-12-30  1.390706 -0.104745  0.174601 -0.082298
2020-12-31 -0.679130 -0.211526 -0.109001 -0.678390

[3653 rows x 4 columns]

In [22]:
df2 = data.pivot_table(index='date',columns='ticker',values='signal1')
df2

ticker          AAPL       BAC        GS      MSFT
date
2011-01-01  0.283229  1.009180  0.424052  0.144383
2011-01-02  0.035900 -1.466306 -2.314417  1.079511
2011-01-03  1.745756 -0.748832  1.174574  0.361653
2011-01-04 -0.830788  0.261571 -1.827015 -0.316657
2011-01-05 -1.551993  0.450485  0.893478 -0.285942
...              ...       ...       ...       ...
2020-12-27 -0.329149 -0.985159 -0.240506 -1.389977
2020-12-28 -0.454955  1.879978 -0.260495  0.486757
2020-12-29  0.644160 -0.957661 -0.742333 -0.091659
2020-12-30  1.390706 -0.104745  0.174601 -0.082298
2020-12-31 -0.679130 -0.211526 -0.109001 -0.678390

[3653 rows x 4 columns]

In [23]:
df1.equals(df2)

True

# Pandas `pivot_table`: Conceptual Summary

## 🧠 Core Idea

`pivot_table` reshapes data from **long format → wide format**, while optionally aggregating duplicate values.

---

## 🔧 Example

    data.pivot_table(
        index='date',
        columns='sector',
        values='signal1',
        aggfunc='mean'
    )

---

## 🧠 What It Does

- Rows (`index`) → unique dates
- Columns (`columns`) → unique sectors
- Values (`values`) → aggregated `signal1` values
- Aggregation (`aggfunc`) → how duplicates are combined

---

## 🔄 Before (Long Format)

| date       | sector | signal1 |
|------------|--------|---------|
| 2021-01-01 | Tech   | 0.5     |
| 2021-01-01 | Tech   | 0.7     |
| 2021-01-01 | Energy | 0.2     |

---

## 🔁 After (Wide Format)

| date       | Tech | Energy |
|------------|------|--------|
| 2021-01-01 | 0.6  | 0.2    |

---

## ⚡ When to Use

Use `pivot_table` when:

- You need to **reshape raw data into a matrix**
- You want to **compare categories side-by-side**
- You have **duplicate combinations** and need aggregation
- You are preparing data for **analysis or modeling**

---

## 🔑 Key Insight

> Pivot transforms “rows of events” into a structured grid of values.

---

## 🧭 Mental Model

- Long format → messy, row-based
- Wide format → structured, column-based

`pivot_table` is the bridge between the two.

---

## ⚠️ Note

If no duplicates exist, you can use:

    data.pivot(...)

If duplicates exist, use:

    data.pivot_table(...)

---

## 💡 Final Takeaway

`pivot_table` makes your data:

- easier to read
- easier to compare
- ready for analysis

In [24]:
data.pivot_table(index='date',columns='sector',values='signal1',aggfunc=np.mean)

sector           Fin      Tech
date
2011-01-01  0.716616  0.213806
2011-01-02 -1.890362  0.557706
2011-01-03  0.212871  1.053704
2011-01-04 -0.782722 -0.573722
2011-01-05  0.671981 -0.918968
...              ...       ...
2020-12-27 -0.612833 -0.859563
2020-12-28  0.809741  0.015901
2020-12-29 -0.849997  0.276250
2020-12-30  0.034928  0.654204
2020-12-31 -0.160263 -0.678760

[3653 rows x 2 columns]

In [25]:
data.pivot_table(index='date',columns='sector',values='signal1',aggfunc=np.max)

sector           Fin      Tech
date
2011-01-01  1.009180  0.283229
2011-01-02 -1.466306  1.079511
2011-01-03  1.174574  1.745756
2011-01-04  0.261571 -0.316657
2011-01-05  0.893478 -0.285942
...              ...       ...
2020-12-27 -0.240506 -0.329149
2020-12-28  1.879978  0.486757
2020-12-29 -0.742333  0.644160
2020-12-30  0.174601  1.390706
2020-12-31 -0.109001 -0.678390

[3653 rows x 2 columns]

## Merge
Check out documentation to learn more: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html

In [26]:
data2=[]
for dt in dates:
    for x in ['Tech','Fin']:
        data2.append([x,dt,np.random.randn(),np.random.randn()])
        
data2 = pd.DataFrame(data2,columns=['sector','date','signal3','signal4'])
data2

     sector       date   signal3   signal4
0      Tech 2011-01-01 -0.128021 -0.001364
1       Fin 2011-01-01  0.222639  0.606904
2      Tech 2011-01-02  1.360479  2.742521
3       Fin 2011-01-02 -1.920426 -1.894007
4      Tech 2011-01-03  0.401644 -0.436587
...     ...        ...       ...       ...
7301    Fin 2020-12-29 -0.019485  0.654231
7302   Tech 2020-12-30  0.594020  0.127479
7303    Fin 2020-12-30  0.892706 -1.403380
7304   Tech 2020-12-31  1.986823  1.147253
7305    Fin 2020-12-31 -1.244451  0.526845

[7306 rows x 4 columns]

# Pandas Merge: Conflicts, Edge Cases, and How to Handle Them

## 🧠 Core Idea

`merge()` combines datasets based on matching keys.

When conflicts occur, Pandas:
- **does not resolve them**
- **preserves all data**
- **forces you to decide what is correct**

---

## 🔧 Basic Example

    df = data.merge(data2, on=['sector','date'])

---

## ⚠️ Edge Case 1: Conflicting Column Values

### Problem

Same keys, different values:

| sector | date       | signal1 |
|--------|------------|--------|
| Tech   | 2021-01-01 | 0.5    |

| sector | date       | signal1 |
|--------|------------|--------|
| Tech   | 2021-01-01 | 0.9    |

---

### Result

| sector | date       | signal1_x | signal1_y |
|--------|------------|-----------|-----------|
| Tech   | 2021-01-01 | 0.5       | 0.9       |

---

### Why This Happens

- Pandas keeps both values to avoid silent data loss
- Adds suffixes:
  - `_x` → left DataFrame
  - `_y` → right DataFrame

---

### How to Handle

#### Choose one source:
    df['signal1'] = df['signal1_x']

#### Combine values:
    df['signal1'] = df[['signal1_x','signal1_y']].mean(axis=1)

#### Detect conflicts:
    (df['signal1_x'] != df['signal1_y']).sum()

---

## ⚠️ Edge Case 2: Duplicate Keys (One-to-Many)

### Problem

Left dataset has duplicate keys:

| sector | date       | signal1 |
|--------|------------|--------|
| Tech   | 2021-01-01 | 0.5    |
| Tech   | 2021-01-01 | 0.6    |

---

### Result

| sector | date       | signal1 | return |
|--------|------------|--------|--------|
| Tech   | 2021-01-01 | 0.5    | 0.01   |
| Tech   | 2021-01-01 | 0.6    | 0.01   |

---

### Why This Happens

- One row in right dataset matches multiple rows in left dataset

---

### How to Handle

#### Remove duplicates:
    data = data.drop_duplicates(subset=['sector','date'])

#### Aggregate first:
    data = data.groupby(['sector','date']).mean().reset_index()

---

## ⚠️ Edge Case 3: Many-to-Many Merge (Data Explosion)

### Problem

Duplicates exist in both datasets.

Example:
- 2 rows in left
- 3 rows in right

👉 Result: 6 rows

---

### Why This Happens

- Every matching row combines with every other matching row

---

### How to Handle

#### Validate merge relationships:
    data.merge(data2, on=['sector','date'], validate='one_to_one')

Other options:
    validate='one_to_many'
    validate='many_to_one'

---

## ⚠️ Edge Case 4: Missing Matches

### Problem

Some keys exist in one dataset but not the other.

---

### Behavior

Default (`how='inner'`):
- Drops unmatched rows

---

### How to Handle

#### Keep all left data:
    data.merge(data2, on=['sector','date'], how='left')

#### Keep everything:
    data.merge(data2, on=['sector','date'], how='outer')

---

## 🧠 Best Practices

### 1. Always check duplicates before merging

    data.duplicated(['sector','date']).sum()

---

### 2. Use `validate` to enforce expectations

    data.merge(data2, on=['sector','date'], validate='one_to_one')

---

### 3. Be explicit about columns

    data.merge(data2[['sector','date','return']], on=['sector','date'])

---

### 4. Inspect results after merge

    df.head()
    df.shape

---

## 🧭 Mental Model

`merge()` does not clean or fix data.

It:

> **combines datasets and exposes inconsistencies**

---

## 🔑 Final Takeaway

- Conflicts are expected
- Pandas preserves all data
- You must define how to resolve inconsistencies

---

## 💡 One Rule to Remember

> Always assume your data is messy and verify before and after every merge

In [27]:
data.merge(data2,left_on=['sector','date'],right_on=['sector','date'])

      ticker sector       date   signal1   signal2   signal3   signal4
0       AAPL   Tech 2011-01-01  0.283229  3.056726 -0.128021 -0.001364
1       MSFT   Tech 2011-01-01  0.144383  0.326354 -0.128021 -0.001364
2        BAC    Fin 2011-01-01  1.009180  1.956001  0.222639  0.606904
3         GS    Fin 2011-01-01  0.424052  1.580517  0.222639  0.606904
4       AAPL   Tech 2011-01-02  0.035900  1.173141  1.360479  2.742521
...      ...    ...        ...       ...       ...       ...       ...
14607     GS    Fin 2020-12-30  0.174601 -0.541720  0.892706 -1.403380
14608   AAPL   Tech 2020-12-31 -0.679130  0.258643  1.986823  1.147253
14609   MSFT   Tech 2020-12-31 -0.678390 -0.853023  1.986823  1.147253
14610    BAC    Fin 2020-12-31 -0.211526 -2.135673 -1.244451  0.526845
14611     GS    Fin 2020-12-31 -0.109001 -0.065435 -1.244451  0.526845

[14612 rows x 7 columns]