In [1]:
import pandas as pd 
import numpy as np 

univ = ['SPY','TLT','VXX','QQQ']
dates = ['20210105','20210106','20210107','20210108','20210109']

In [2]:
earnings = pd.DataFrame(np.random.randn(5,4), index=dates,columns=univ)
ret_prev = pd.DataFrame(np.random.randn(5,4), index=dates,columns=univ)
pe = pd.DataFrame( np.random.randn(5,4), index=dates,columns=univ)
analyst_est = pd.DataFrame( np.random.randn(5,4), index=dates,columns=univ)

In [3]:
pe

               SPY       TLT       VXX       QQQ
20210105 -0.083112 -0.293528  0.432116 -0.638812
20210106 -1.276291 -0.231925  0.571817  1.135198
20210107  0.348323  1.104844  0.389644  0.491030
20210108  1.112694  0.158161 -0.928032  0.973266
20210109  0.679968 -2.209587 -1.294063  0.304355

In [4]:
data = {}
data['earnings']=earnings
data['ret_prev']=ret_prev
data['pe']=pe
data['analyst_est']=analyst_est

In [5]:
data

{'earnings':                SPY       TLT       VXX       QQQ
 20210105  0.874712  1.482826 -0.266140  1.083576
 20210106  0.504568 -0.856350 -1.164751  0.661141
 20210107 -0.139940  0.146541 -0.841031  0.787053
 20210108 -0.882431  0.429994  0.267027 -1.077473
 20210109 -1.433594  0.377630 -1.299715 -0.467705,
 'ret_prev':                SPY       TLT       VXX       QQQ
 20210105 -0.649596 -0.060684  0.303461 -0.892449
 20210106  0.697599  0.347878 -0.244919  0.596254
 20210107  1.262910  0.941813 -0.213185 -1.054797
 20210108  0.905851 -0.884529  1.590356  0.059721
 20210109 -2.330266  0.335115  1.836903 -1.525910,
 'pe':                SPY       TLT       VXX       QQQ
 20210105 -0.083112 -0.293528  0.432116 -0.638812
 20210106 -1.276291 -0.231925  0.571817  1.135198
 20210107  0.348323  1.104844  0.389644  0.491030
 20210108  1.112694  0.158161 -0.928032  0.973266
 20210109  0.679968 -2.209587 -1.294063  0.304355,
 'analyst_est':                SPY       TLT       VXX       QQQ
 20210105 -0.534139  0.432123  0.349592 -1.355784
 20210106  0.904355 -0.628835 -0.400962  0.028231
 20210107 -1.197400 -1.391018  0.829287  0.660650
 20210108 -0.695499 -1.355421  0.602758 -1.226985
 20210109  2.626112  1.502196  1.228757  0.571921}

In [6]:
multi = pd.concat(data)
multi

                           SPY       TLT       VXX       QQQ
earnings    20210105  0.874712  1.482826 -0.266140  1.083576
            20210106  0.504568 -0.856350 -1.164751  0.661141
            20210107 -0.139940  0.146541 -0.841031  0.787053
            20210108 -0.882431  0.429994  0.267027 -1.077473
            20210109 -1.433594  0.377630 -1.299715 -0.467705
ret_prev    20210105 -0.649596 -0.060684  0.303461 -0.892449
            20210106  0.697599  0.347878 -0.244919  0.596254
            20210107  1.262910  0.941813 -0.213185 -1.054797
            20210108  0.905851 -0.884529  1.590356  0.059721
            20210109 -2.330266  0.335115  1.836903 -1.525910
pe          20210105 -0.083112 -0.293528  0.432116 -0.638812
            20210106 -1.276291 -0.231925  0.571817  1.135198
            20210107  0.348323  1.104844  0.389644  0.491030
            20210108  1.112694  0.158161 -0.928032  0.973266
            20210109  0.679968 -2.209587 -1.294063  0.304355
analyst_est 20210105 -0.534139  0.432123  0.349592 -1.355784
            20210106  0.904355 -0.628835 -0.400962  0.028231
            20210107 -1.197400 -1.391018  0.829287  0.660650
            20210108 -0.695499 -1.355421  0.602758 -1.226985
            20210109  2.626112  1.502196  1.228757  0.571921

In [7]:
multi.loc['pe']

               SPY       TLT       VXX       QQQ
20210105 -0.083112 -0.293528  0.432116 -0.638812
20210106 -1.276291 -0.231925  0.571817  1.135198
20210107  0.348323  1.104844  0.389644  0.491030
20210108  1.112694  0.158161 -0.928032  0.973266
20210109  0.679968 -2.209587 -1.294063  0.304355

In [9]:
# For key and specific column.  mult.loc['key label', 'column name']
multi.loc['pe', 'SPY']

20210105   -0.083112
20210106   -1.276291
20210107    0.348323
20210108    1.112694
20210109    0.679968
Name: SPY, dtype: float64

In [10]:
# slicing
multi.loc['ret_prev':'analyst_est'] # includes ret_prev, pe, and analyst_est

                           SPY       TLT       VXX       QQQ
ret_prev    20210105 -0.649596 -0.060684  0.303461 -0.892449
            20210106  0.697599  0.347878 -0.244919  0.596254
            20210107  1.262910  0.941813 -0.213185 -1.054797
            20210108  0.905851 -0.884529  1.590356  0.059721
            20210109 -2.330266  0.335115  1.836903 -1.525910
pe          20210105 -0.083112 -0.293528  0.432116 -0.638812
            20210106 -1.276291 -0.231925  0.571817  1.135198
            20210107  0.348323  1.104844  0.389644  0.491030
            20210108  1.112694  0.158161 -0.928032  0.973266
            20210109  0.679968 -2.209587 -1.294063  0.304355
analyst_est 20210105 -0.534139  0.432123  0.349592 -1.355784
            20210106  0.904355 -0.628835 -0.400962  0.028231
            20210107 -1.197400 -1.391018  0.829287  0.660650
            20210108 -0.695499 -1.355421  0.602758 -1.226985
            20210109  2.626112  1.502196  1.228757  0.571921

## Understanding `.loc` with a MultiIndex DataFrame

This DataFrame was created using `pd.concat(data)`, which results in a **MultiIndex**:

- **Level 0 (outer index):** data type (e.g., `'earnings'`, `'ret_prev'`, `'pe'`, `'analyst_est'`)
- **Level 1 (inner index):** dates (e.g., `'20210107'`)

Each row is identified by a tuple:
`('ret_prev', '20210107')`

---

### Command Breakdown (following cell)

`multi.loc[('ret_prev','20210107'), ['SPY','TLT']]`

#### 1. `.loc`
- Label-based indexing (uses index names, not positions)

#### 2. Row Selection
`('ret_prev','20210107')`

- Selects the row where:
  - Level 0 = `'ret_prev'`
  - Level 1 = `'20210107'`

#### 3. Column Selection
`['SPY','TLT']`

- Selects only these two columns from that row

---

### Result

Returns the values for SPY and TLT for `'ret_prev'` on `'20210107'`:

```
SPY    1.262910
TLT    0.941813
```

---

### Key Takeaways

- `.loc` uses **labels**, not positions
- MultiIndex rows require a **tuple**: `(level_0, level_1)`
- Columns are selected like a normal list

In [12]:
# multi.loc[('ret_prev','20210107'), ['SPY','TLT']]
#
# Explanation:
# This DataFrame uses a MultiIndex created by pd.concat(data), where:
#   - Level 0 index = data type (e.g., 'earnings', 'ret_prev', etc.)
#   - Level 1 index = date (e.g., '20210107')
#
# ('ret_prev','20210107') is a tuple that selects a specific row:
#   - 'ret_prev' → first index level
#   - '20210107' → second index level
#
# ['SPY','TLT'] selects only those columns from that row
#
# Result:
# Returns the SPY and TLT values for 'ret_prev' on '20210107'
#
# Key idea:
#   - .loc = label-based indexing
#   - MultiIndex requires tuple-based row selection

multi.loc[('ret_prev','20210107'),['SPY','TLT']]

SPY    1.262910
TLT    0.941813
Name: (ret_prev, 20210107), dtype: float64

### Selecting a Single Column from a MultiIndex DataFrame

```python
ser = multi['SPY']
```

---

### What This Does

- `multi` is a **DataFrame** with multiple columns (SPY, TLT, VXX, QQQ)
- Selecting a single column (`'SPY'`) returns a **Series**

#### Why a Series?
- A **DataFrame** is 2-dimensional (rows + columns)
- A **Series** is 1-dimensional (a single column of data)

So:
```python
multi['SPY']
```
returns a **Series** because only one column is selected.

---

### What the Result Looks Like

The resulting `ser` still keeps the **MultiIndex**:

```
earnings      20210105    0.8747
              20210106    0.5045
...
ret_prev      20210107    1.2629
...
pe            20210108    1.1127
...
analyst_est   20210109    2.6261
```

- Index = `(category, date)`
- Values = SPY data

---

### Purpose of Creating a Series

#### 1. Focus on a Single Variable
Instead of working with all columns:
```python
multi
```

You isolate one:
```python
ser
```

---

#### 2. Easier MultiIndex Slicing

```python
ser.loc['ret_prev']
```

Returns:
```
20210105   -0.6496
20210106    0.6976
20210107    1.2629
...
```

---

#### 3. Useful for Analysis and Modeling

Working with a Series makes it easier to:
- Compute statistics (`mean`, `std`)
- Apply transformations (`pct_change`, rolling averages)
- Use as input for models

Example:
```python
ser.mean()
ser.std()
ser.pct_change()
```

---

#### 4. Cleaner Data Manipulation

A Series simplifies operations compared to handling multiple columns at once.

---

### Important Detail

```python
multi['SPY']     # returns a Series
multi[['SPY']]   # returns a DataFrame
```

- Single brackets → Series
- Double brackets → DataFrame

---

### Key Takeaways

- Selecting one column returns a **Series**
- The **MultiIndex is preserved**
- Series are easier to work with for analysis and modeling

In [15]:
ser = multi['SPY']
ser

earnings     20210105    0.874712
             20210106    0.504568
             20210107   -0.139940
             20210108   -0.882431
             20210109   -1.433594
ret_prev     20210105   -0.649596
             20210106    0.697599
             20210107    1.262910
             20210108    0.905851
             20210109   -2.330266
pe           20210105   -0.083112
             20210106   -1.276291
             20210107    0.348323
             20210108    1.112694
             20210109    0.679968
analyst_est  20210105   -0.534139
             20210106    0.904355
             20210107   -1.197400
             20210108   -0.695499
             20210109    2.626112
Name: SPY, dtype: float64

In [16]:
# Working with the Series.  Pass in the key label, the output are the inner key and values.
ser['pe']

20210105   -0.083112
20210106   -1.276291
20210107    0.348323
20210108    1.112694
20210109    0.679968
Name: SPY, dtype: float64

## Below is an example of working with a DataFrame from a MultiIndex DataFrame

In [17]:
df_spy = multi[['SPY']]
df_spy

                           SPY
earnings    20210105  0.874712
            20210106  0.504568
            20210107 -0.139940
            20210108 -0.882431
            20210109 -1.433594
ret_prev    20210105 -0.649596
            20210106  0.697599
            20210107  1.262910
            20210108  0.905851
            20210109 -2.330266
pe          20210105 -0.083112
            20210106 -1.276291
            20210107  0.348323
            20210108  1.112694
            20210109  0.679968
analyst_est 20210105 -0.534139
            20210106  0.904355
            20210107 -1.197400
            20210108 -0.695499
            20210109  2.626112

In [11]:
# unstack a multindex series into a dataframe
ser.unstack(level=0)

          earnings  ret_prev        pe  analyst_est
20210105  0.027917  0.417888  0.360900     0.853645
20210106 -2.508643  1.204926 -0.413056    -0.389263
20210107  0.776489 -1.569208  0.240933    -0.457811
20210108  0.282424  0.370359 -2.448689    -1.531211
20210109 -0.826999  0.211030  1.407146    -0.449169

In [12]:
ser.unstack(level=0).stack()

20210105  earnings       0.027917
          ret_prev       0.417888
          pe             0.360900
          analyst_est    0.853645
20210106  earnings      -2.508643
          ret_prev       1.204926
          pe            -0.413056
          analyst_est   -0.389263
20210107  earnings       0.776489
          ret_prev      -1.569208
          pe             0.240933
          analyst_est   -0.457811
20210108  earnings       0.282424
          ret_prev       0.370359
          pe            -2.448689
          analyst_est   -1.531211
20210109  earnings      -0.826999
          ret_prev       0.211030
          pe             1.407146
          analyst_est   -0.449169
dtype: float64

In [13]:
multi = pd.concat(data,1)

In [14]:
multi

          earnings                                ret_prev            \
               SPY       TLT       VXX       QQQ       SPY       TLT
20210105  0.027917  0.997937 -0.813769  1.427540  0.417888  1.398934
20210106 -2.508643 -0.955644  0.148005  1.389984  1.204926  0.362746
20210107  0.776489 -0.217345 -0.798040  0.133415 -1.569208  0.141109
20210108  0.282424 -0.884986  0.046271  0.145123  0.370359  1.688694
20210109 -0.826999  0.566471  2.485849  0.204731  0.211030 -0.630121

                                    pe                                \
               VXX       QQQ       SPY       TLT       VXX       QQQ
20210105 -0.443163  1.199215  0.360900  1.245730 -0.457611  0.100197
20210106 -1.818578  0.197606 -0.413056 -0.161820 -0.187747  0.140069
20210107 -0.195729  1.945500  0.240933  0.195412  1.095961 -0.224336
20210108  1.257109  0.543659 -2.448689 -1.464831  1.182993 -0.713982
20210109  0.152533  0.697834  1.407146 -0.072162 -0.078432 -0.667566

         analyst_est
                 SPY       TLT       VXX       QQQ
20210105    0.853645 -0.327806 -0.849994 -0.901581
20210106   -0.389263 -0.252517  0.722480  0.334567
20210107   -0.457811  0.846454 -1.187873 -1.526764
20210108   -1.531211 -0.984030 -0.749255  1.768825
20210109   -0.449169 -1.935268  0.120385 -0.003290

In [15]:
# indexing
multi['pe']

               SPY       TLT       VXX       QQQ
20210105  0.360900  1.245730 -0.457611  0.100197
20210106 -0.413056 -0.161820 -0.187747  0.140069
20210107  0.240933  0.195412  1.095961 -0.224336
20210108 -2.448689 -1.464831  1.182993 -0.713982
20210109  1.407146 -0.072162 -0.078432 -0.667566

In [16]:
multi[['pe','earnings']]

                pe                                earnings            \
               SPY       TLT       VXX       QQQ       SPY       TLT
20210105  0.360900  1.245730 -0.457611  0.100197  0.027917  0.997937
20210106 -0.413056 -0.161820 -0.187747  0.140069 -2.508643 -0.955644
20210107  0.240933  0.195412  1.095961 -0.224336  0.776489 -0.217345
20210108 -2.448689 -1.464831  1.182993 -0.713982  0.282424 -0.884986
20210109  1.407146 -0.072162 -0.078432 -0.667566 -0.826999  0.566471


               VXX       QQQ
20210105 -0.813769  1.427540
20210106  0.148005  1.389984
20210107 -0.798040  0.133415
20210108  0.046271  0.145123
20210109  2.485849  0.204731

In [17]:
# rearrange axes
multi.swaplevel(0,1,1)

,SPY,TLT,VXX,QQQ,SPY,TLT,VXX,QQQ,SPY,TLT,VXX,QQQ,SPY,TLT,VXX,QQQ
,earnings,earnings,earnings,earnings,ret_prev,ret_prev,ret_prev,ret_prev,pe,pe,pe,pe,analyst_est,analyst_est,analyst_est,analyst_est
20210105,0.027917,0.997937,-0.813769,1.427540,0.417888,1.398934,-0.443163,1.199215,0.360900,1.245730,-0.457611,0.100197,0.853645,-0.327806,-0.849994,-0.901581
20210106,-2.508643,-0.955644,0.148005,1.389984,1.204926,0.362746,-1.818578,0.197606,-0.413056,-0.161820,-0.187747,0.140069,-0.389263,-0.252517,0.722480,0.334567
20210107,0.776489,-0.217345,-0.798040,0.133415,-1.569208,0.141109,-0.195729,1.945500,0.240933,0.195412,1.095961,-0.224336,-0.457811,0.846454,-1.187873,-1.526764
20210108,0.282424,-0.884986,0.046271,0.145123,0.370359,1.688694,1.257109,0.543659,-2.448689,-1.464831,1.182993,-0.713982,-1.531211,-0.984030,-0.749255,1.768825
20210109,-0.826999,0.566471,2.485849,0.204731,0.211030,-0.630121,0.152533,0.697834,1.407146,-0.072162,-0.078432,-0.667566,-0.449169,-1.935268,0.120385,-0.003290

In [18]:
multi.swaplevel(0,1,1).sort_index(1)

                 QQQ                                       SPY            \
         analyst_est  earnings        pe  ret_prev analyst_est  earnings
20210105   -0.901581  1.427540  0.100197  1.199215    0.853645  0.027917
20210106    0.334567  1.389984  0.140069  0.197606   -0.389263 -2.508643
20210107   -1.526764  0.133415 -0.224336  1.945500   -0.457811  0.776489
20210108    1.768825  0.145123 -0.713982  0.543659   -1.531211  0.282424
20210109   -0.003290  0.204731 -0.667566  0.697834   -0.449169 -0.826999

                                     TLT                                \
                pe  ret_prev analyst_est  earnings        pe  ret_prev
20210105  0.360900  0.417888   -0.327806  0.997937  1.245730  1.398934
20210106 -0.413056  1.204926   -0.252517 -0.955644 -0.161820  0.362746
20210107  0.240933 -1.569208    0.846454 -0.217345  0.195412  0.141109
20210108 -2.448689  0.370359   -0.984030 -0.884986 -1.464831  1.688694
20210109  1.407146  0.211030   -1.935268  0.566471 -0.072162 -0.630121

                 VXX
         analyst_est  earnings        pe  ret_prev
20210105   -0.849994 -0.813769 -0.457611 -0.443163
20210106    0.722480  0.148005 -0.187747 -1.818578
20210107   -1.187873 -0.798040  1.095961 -0.195729
20210108   -0.749255  0.046271  1.182993  1.257109
20210109    0.120385  2.485849 -0.078432  0.152533

In [19]:
# sum across an axis
multi.sum(axis=1,level=0)

          earnings  ret_prev        pe  analyst_est
20210105  1.639625  2.572874  1.249216    -1.225737
20210106 -1.926297 -0.053300 -0.622554     0.415266
20210107 -0.105480  0.321673  1.307971    -2.325994
20210108 -0.411167  3.859821 -3.444509    -1.495671
20210109  2.430052  0.431277  0.588986    -2.267342

In [20]:
# standard pandas functions produce multi-index series
multi.mean()

earnings     SPY   -0.449762
             TLT   -0.098713
             VXX    0.213663
             QQQ    0.660159
ret_prev     SPY    0.126999
             TLT    0.592273
             VXX   -0.209566
             QQQ    0.916763
pe           SPY   -0.170553
             TLT   -0.051534
             VXX    0.311033
             QQQ   -0.273124
analyst_est  SPY   -0.394762
             TLT   -0.530634
             VXX   -0.388851
             QQQ   -0.065649
dtype: float64

In [21]:
multi.mean().unstack(level=1)

                  SPY       TLT       VXX       QQQ
earnings    -0.449762 -0.098713  0.213663  0.660159
ret_prev     0.126999  0.592273 -0.209566  0.916763
pe          -0.170553 -0.051534  0.311033 -0.273124
analyst_est -0.394762 -0.530634 -0.388851 -0.065649